In [1]:
import pandas as pd
import numpy as np

In [15]:
data = pd.read_csv('Data/NEISS/all_fracture.csv')

In [16]:
sports= data.loc[data['location']==9]

In [19]:
sports['prod2'] = sports['prod2'].fillna(0.0).astype(int) # I may need to change this. An error is being thrown

np.unique(sports[['prod1','prod2']])

/Users/jamesbain/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


array([   0,  102,  131,  136,  137,  215,  216,  242,  263,  374,  379,
        393,  394,  413,  464,  465,  466,  478,  536,  546,  547,  550,
        557,  566,  572,  604,  611,  612,  613,  617,  639,  648,  649,
        653,  654,  661,  666,  676,  679,  685,  687,  698,  699,  707,
        814,  827,  832,  835,  837,  845,  852,  884,  885,  886,  899,
        913,  960, 1023, 1062, 1107, 1112, 1114, 1120, 1127, 1133, 1137,
       1138, 1141, 1143, 1144, 1200, 1205, 1206, 1207, 1208, 1211, 1212,
       1213, 1215, 1217, 1233, 1234, 1235, 1237, 1239, 1242, 1243, 1244,
       1257, 1258, 1260, 1261, 1264, 1266, 1267, 1269, 1270, 1271, 1272,
       1273, 1275, 1276, 1277, 1278, 1279, 1282, 1283, 1284, 1290, 1293,
       1294, 1295, 1299, 1301, 1309, 1310, 1313, 1317, 1322, 1325, 1327,
       1328, 1329, 1330, 1333, 1342, 1347, 1349, 1352, 1381, 1392, 1394,
       1395, 1398, 1403, 1406, 1413, 1414, 1415, 1422, 1425, 1426, 1439,
       1457, 1465, 1466, 1502, 1506, 1512, 1519, 15

In [17]:
sports

Unnamed: 0  CPSC Case #   trmt_date  psu   weight stratum  age  \
0                4     90101437  2009-01-01   61  15.3491       V   20   
1                5     90101438  2009-01-01   61  15.3491       V   47   
10              83     90101933  2009-01-01    1  70.8387       S   12   
11              96     90101967  2009-01-03    1  70.8387       S   57   
16             135     90102965  2009-01-01   69  62.0610       L   23   
23             193     90103756  2009-01-01   32   6.0260       C   11   
24             211     90103810  2009-01-01   67  15.3491       V   15   
55             448     90106127  2009-01-02   44  62.0610       L   34   
56             458     90106172  2009-01-03   61  15.3491       V   16   
57             461     90106184  2009-01-03   61  15.3491       V   21   
59             471     90106203  2009-01-02   50  62.0610       L   10   
61             501     90106272  2009-01-02   61  15.3491       V   13   
62             503     90106276  2009-01-02   61  15.3491       V   12   
64             536     90106344  2009-01-01   55  62.0610       L   13   
68             565     90106752  2009-01-03   99  70.8387       S    9   
76             687     90107063  2009-01-03   25  15.3491       V   34   
77             688     90107117  2009-01-01   47  70.8387       S   17   
78             689     90107119  2009-01-02   47  70.8387       S   47   
82             739     90107832  2009-01-02   42  62.0610       L   10   
84             758     90107874  2009-01-03   42  62.0610       L   29   
90             812     90108040  2009-01-02   59  70.8387       S   11   
91             813     90108041  2009-01-02   59  70.8387       S   42   
93             818     90108046  2009-01-02   59  70.8387       S   11   
94             821     90108049  2009-01-02   59  70.8387       S   24   
95             823     90108051  2009-01-03   59  70.8387       S   14   
96             825     90108053  2009-01-03   59  70.8387       S   64   
99             830     90108058  2009-01-03   59  70.8387       S   16   
100            834     90108062  2009-01-03   59  70.8387       S   12   
101            835     90108063  2009-01-03   59  70.8387       S   13   
102            836     90108064  2009-01-04   59  70.8387       S   19   
...            ...          ...         ...  ...      ...     ...  ...   
346053      366620    150105783  2014-12-27   21  15.6716       V   12   
346056      366658    140756125  2014-07-08   38  15.6716       V    8   
346063      366697    140244689  2014-02-09   38  14.3089       V   24   
346066      366715    140510468  2014-05-03   21  14.3089       V   14   
346069      366722    140244721  2014-02-07   38  14.3089       V   19   
346070      366724    140443715  2014-04-19   21  14.3089       V   21   
346077      366779    140432833  2014-04-07   38  14.3089       V   17   
346080      366792    140451852  2014-04-13   38  14.3089       V   33   
346081      366794    140512806  2014-05-04   21  14.3089       V   38   
346082      366795    140821464  2014-08-03   21  15.6716       V   12   
346087      366824    140512722  2014-05-04   21  14.3089       V   13   
346091      366848    140926106  2014-08-27   38  15.6716       V    7   
346092      366858    141125087  2014-11-09   21  15.6716       V   25   
346106      366969    141012557  2014-09-30   21  15.6716       V   13   
346109      366979    140534616  2014-05-15   21  14.3089       V    9   
346115      367011    140756177  2014-07-14   38  15.6716       V   15   
346118      367024    140510375  2014-05-02   21  14.3089       V   15   
346126      367076    140801330  2014-07-18   21  15.6716       V    8   
346127      367084    141207421  2014-11-28   21  15.6716       V    8   
346131      367128    140835039  2014-08-14   21  15.6716       V    6   
346134      367157    141233465  2014-12-09   38  15.6716       V   25   
346147      367198    141227562  2014-12-04   38  15.6716       V   43   
346148      

array([ 6566,  2422,  6432,  2434,  6510,  2666, 10062,  6554,  6572,
        2580, 10068,  2534, 10082,  6544,  2412,  6598,  6508,  6518,
        2410,  2522,  2540,  6444,  2532, 10072,  2586,  2488,  6548,
        2414,  6512,  6434,  2544,  2516,  2598,  2484,  6514,  2558,
        1920,  2430,  6502, 10080,  2478,  2424,  6546,  6492,  6470,
        6556,  3774,  6594,  6530, 10066,  2400,  1222,  8148,  2466,
        3786,  2546,  6568,  6446,  2828,  6468,  8152,  3742,  2588,
        3768,  1374,  6472,  3790,  3614,  2634,  2568,  6490,  3684,
        2486,  6574,  2590,  1704,  6576, 10008,  6438, 10060,  6564,
       10064,  2426,  2660,  8156,  2796,  3658, 10084,  3054,  2658,
        2552,  1298,  3634,  1352,  3290,  3686,  6442,  3730,  3212,
        2556,  1072,  2528, 10032,  3412,  6590,  8114,  2564,  2550,
        2852,  3430,  3230,  1308,   748,  1628,  6400, 10058,  6588,
        1670,  3368,  6404,  6524,  2468,  1654,  2626,  2844,  6586,
        6552,  2228,

In [26]:
prod_cleaner(uniq_prod2)

array([ 3686,  3730, 10062,  6566,  3768,  2410, 10058,  6502,  3230,
        6556,  2466,  3742,  2598,  2544,  2414,  2424,  6572,  3614,
        6434,  3658,  6514,  3714,  2534,  6492,  1374,  2540,  8114,
        6544,  3684,  6530,  6598,  2224,  6432, 10082,  6470,  1352,
        2658,  3412,  2484,  6574,  2588,  2878,  2488,  2532,  3090,
        1224,  6546, 10008,  3634, 10080,  2468,  6438,  2426,  2666,
        3290,  6446,  2288,  1332,  2556, 10068,  2400,  3212,  6554,
        1704,  2568,  3316,  8032,  2478,  3294,  3788,  8020,  6548,
        8156,  8148,  2422,  2046,  1072,  3624, 10072,  6568,  2586,
        2282,  2434,  3476,  1100, 10032,  3786,  8112,  3790,  2930,
        2240,  3368,  6594,  2516,  6524,   748,  1358,  3044,  2412,
        3774,  2812, 10034,  3214,  6510,  6512, 10022,  8160,  6400,
        2554,  2558,  3778,  6590,  6508,  8016, 10060,  3224,  3638,
        6518,  2626,   272,  3756,  3740, 10084,  3770,  2266,   826,
        1654,  3232,